<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<h2>Signup to Dinner</h2>
<iframe style="width:75% ; height:40em " 
src="https://forms.gle/qiFYhbWUtJxvFr3cA">
</iframe>
<p>

<h2>Participants</h2>

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSUDh73IOVUvuUl_EAkBWzciV_pv8dOxlh4cqilJjVprMAE4ti0MIyk1EmKNMr7nTZ4ITtU3CqpJynO/pubhtml?widget=true&amp;headers=false"></iframe>

    <!--
<iframe style="width:75% ; height:400em " 
src="https://docs.google.com/spreadsheets/d/1s_3zr8qdCzYlO1vjdVLP_fw5mqlOgfrlmN5Tq2Zt31o/edit?resourcekey=&gid=1489952670#gid=1489952670">
-->
</iframe>

</body>
</html>