<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>



</head>
<body class="Back">
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img   class="ResponsiveImage"  src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12">
             <center>
            <?php include "./imports_/title.php" ?>
            </center>
       </div>
    </div>

</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 
                  <?php include "./imports_/navlink.php" ?>
             </div>
      <div class="col-sm-1"> </div> 
      </div>
  
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  



  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-2 ">
            <p>
     

        
        

        </div>
        <div class="col-sm-9">
            <p>The Santa Clara Tennis Club Board meets via the <a href="https://zoom.us/download":>Zoom</a> app.
                  Meetings begin at 7:00pm and are open to all interested parties.  Email for the Zoom invite.
                  <p>
                        President &nbsp;   Bob Brunkhorst&nbsp; prezz@<br>
                        Vice President &nbsp;   Ken Okazaki &nbsp; veep@<br>
                       Secretary &nbsp;   Jose Contreras &nbsp;  sec@<br>
                 Treasurer &nbsp; Carrie Bell&nbsp; treas@<br>
                 Membership &nbsp; memb@           <br>
                 Communications &nbsp; Jeanette Hoggart &nbsp;comm@<br>
                 Social Media &nbsp; Helen Matsumoto &nbsp; socmed@          <br>
                 Clinics &nbsp; Rich Wilder &nbsp; clinic@          <br>
                 Socials &nbsp; Roy Molseed &nbsp; social@            <br>
                 &emsp; &emsp;  &emsp; &nbsp; Megan Chang &nbsp social@ <br>
                 USTA &nbsp; Alice Isaacson &nbsp; ustacoord@             <br>
                 Webmaster &nbsp; Roger Okamoto &nbsp; webmaster@ <br>
                 
                  Board &nbsp; board@   <p>
               <p> 
                  
            <h3>Tennis Instruction</h3>
               <a href="http://www.lifetimetennis.com">Lifetime Tennis</a>
<!--              
               <p>Parks &amp; Rec<br>Milee Beaulieu<br>408-615-3160<p>
-->
               <hr/>
      
                <b>Board Notes 2023-2024 </b><br>
        <?php
         
//                 chdir("./board_");
//                 echo ("dir = ".getcwd() ."<br>");
//            include("./board_/enumerate.php");

        ?>
        <p>
            <b><a href="./docs/sctcbylaws.pdf">By-Laws</a></b>
        <p>

        <b>2024</b><br>
        <a href="./docs/board/2024/2024_Feb.pdf">2024 Feb</a>   <br>
        <a href="./docs/board/2024/2024_June.pdf">2024 June</a>  <br>
        <a href="./docs/board/2024/2024_Sept.pdf">2024 Sept</a>  <br>
                
        <p/>

        <b>2023</b><br>
        <a href="./docs/board/2023/2023_Feb.pdf">2023 Feb</a>   <br>
        <a href="./docs/board/2023/2023_June.pdf">2023 June</a>   <br>
        <a href="./docs/board/2023/2023_Oct.pdf">2023 Oct</a>   <br>
        <p>
         

      </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
          <?php
            include "./imports_/footer.php";
          ?>

        </div>

      
</body>
</html>