<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <style>
      .hidden{

            display: none

      }

      .errmessage{
            font-size: 1.3em;
            color: purple;
            font-weight: bold;

      }

      .message {
            font-size: 1.2em;
            color: black;
            font-weight: normal;


      }

       </style>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
      <script src="http://code.jquery.com/jquery-latest.min.js"></script>


      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>

      <script defer >

             //  ASYNCHRONOUS new stuff ********
               function resolver(_data){

                  var span = document.getElementById("message")
                         if(_data == "yes"){
                                    $("#MemberList").css("display","inline");
                                    $("#message").addClass('errmessage');
                                    span.innerHTML = span.innerText = span.textContent =  "<b> Match Results recorded </b>"
                          //          alert(span.innerHTML);
                                    $("#but_submit").attr("disabled", true);
                                    $("#but_submit").prop("value", "button disabled");

                        }else{

                                    $("#MemberList").css("display","none");
                                                                        
                                    span.innerHTML = span.innerText = span.textContent =  "<b>Cant find " + _data + " email address, try again with your SCTC email address</b>"
                                    $("#message").addClass('message');
                                    alert(span.innerHTML);

                                }



            }


            async function  fetchData( ) {
                   return new Promise((resolve, reject) => {
//                        let user = $("#user").val()
//                        let pw = $("#pw").val()
                        let winner_id = $("#winner").val()
                        let loser_id = $("#loser").val()

                        let score = $("#score").val()
                        let email = $("#email").val()
                        let division = $("#division").val()
                        let gender = $("#gender").val()
        
                      $.ajax({
                        
                              url: "./code_/ladder_recordscore.php",
                              type: "post",
                              data:{ winner_id: winner_id , loser_id:loser_id ,score:score , email:email, division: division , gender: gender },
                              dataType: "html",
                              success: (data) => {
                                   //  alert("resolve " + data )
                                      resolver(data);

                              },
                                    error: (error) => {
                                      reject(error);
                                    }
                });
              });
            }



            document.addEventListener('DOMContentLoaded', function() {
                  $("#MemberList").css("display","none");
     //             $("#but_submit").prop('value', 'Submit to get membership list');
     //             $("#but_submit").attr('value', 'Submitter');

                  $("#but_submit").click( function(){

                        fetchData( )


                     })
              }, false);
            
              
              $(document).ready(
                 // $("#but_submit").val("New Label");
//                  document.getElementById("#but_submit").innerHTML = "Button Listener";
//                  $("#but_submit").attr('value', 'Submitter( defer) ');
/*
                     $("#but_submit").click( function(){

                     })
*/

            )

      </script>


</head>
<body class="Back" >
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage"  src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12 "> 
            <center>
                  <?php include "./imports_/title.php" ?>
             </center>
    </div>
     </div>

</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 
                  <?php include "./imports_/navlink.php" ?>
             </div>

      <div class="col-sm-1"> </div> 
      </div>
  
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  
<!--  **************************************************************  -->
      <div class="container-sm"  > 
            <div class="row">
            <div class="col-sm-2">&nbsp;</div>
            <div class="col-sm-8 text-center">
                <span id="message">  Message </span>      
            </div>
            <div class="col-sm-2">&nbsp;</div>

            
      </div>




 <!--  **************************************************************  -->


      <div class="container" id="LadderList" >
      <div class="row align-items-start">
        <div class="col-sm-1 ">
            <p>
     
        </div>
        <div class="col-sm ">

        <?php
               include("./library/include.inc");
               include("./code_/ladder.php");
        ?>


        </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
 
        <?php
         include "./imports_/footer.php";
        ?>

        
        </div>







<body>
      
</body>
</html>