<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <link rel="stylesheet" href="./css/draw.css" >

      <title>Santa Clara Tennis Club</title>



</head>
<body class="Back" >
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage"  src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12 "> 
            <center>
                  <?php include "./imports_/title.php" ?>
             </center>
    </div>
     </div>

</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-2"> </div> 
            <div class="col-sm-8 NavLink"> 
            <?php include "./imports_/debug.php" ?>  
              
             </div>

      <div class="col-sm-2"> </div> 
      </div>
  
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  

  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-1 ">
            <p>
     
        </div>
        <div class="col-sm ">

        <?php
 //              include("./library/include.inc");
 //              include("./members_/memberlist.php");
        ?>
 
<style>


  main{
    display:flex;
    flex-direction:row;
  }


</style>
   <?php
           include "./library/include.inc";


           function TEXTER($v){

            echo("$v <br>");
           }

           $mode = 0;

           if( !empty($_GET['mode']) ){
                $mode=$_GET["mode"];
           }
            

          if($mode == 0 ){
              echo("DEBUGGING MODE ");

           }else if($mode == 1){
            $_POST["mode"]=1;
            include "./tournament_/reorder.php";  
           }else if($mode == 2) {
            $_POST["mode"]=2;
            include "./tournament_/reorder.php";  
           }else if($mode == 3){
            $_POST["mode"]=3;
            include "./tournament_/reorder.php";  
           }else if($mode == 4){  
            $_POST["mode"]=4;
            include "./tournament_/reorder.php";  

           } else if($mode == 10 ){
            $draw=TOURNY_MEN;
            $TABLE_TOURNY = TABLE_TOURNY;
            $YEAR=YEAR;

            $QUARTERS= TOURNY_MEN_QUARTERS;
            $SEMIS = TOURNY_MEN_SEMIS;
            $FINALS= TOURNY_MEN_FINALS;
//          $DEBUG="NOPE";
            $SCORE="NTEXT";


            $TEAM="NOPE";
            $TEAM="NTEXT";


            $TEAM = "NTEXT";
            $DEBUG="DTEXT";
            echo(" <h3> $YEAR $draw Tournament </h3> ");
            include "./tournament_/draw.php";  
           } else if( $mode==11){
            $draw=TOURNY_WOMYN;//"Mx6.5";               //TOURNY_MEN; //"7.5";
            $TABLE_TOURNY = TABLE_TOURNY;
            $YEAR=YEAR;

            $QUARTERS= TOURNY_WOMYN_QUARTERS;
            $SEMIS = TOURNY_WOMYN_SEMIS;
            $FINALS= TOURNY_WOMYN_FINALS;

            $TEAM="NOPE";
            $TEAM="NTEXT";

            $SCORE="NTEXT";

            $DEBUG="NOPE";
            $DEBUG="DTEXT";


            echo(" <h3> $YEAR $draw Tournament </h3> ");
            include "./tournament_/draw.php"; 

           }else if( $mode == 20){
            
            include "./tournament_/db.php";  
   
           }else if( $mode == 21 ){

            include "./tournament_/logger.php";  
           
          } else if($mode==99){
// do nothing

      }


?>
  

</div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
 
        <?php
         include "./imports_/footer.php";
        ?>

        
        </div>







<body>
      
</body>
</html>