<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/draw.css" >

</head>
<style>

.round{
    display:flex;
    flex-direction:column;
    justify-content:center;
    width:200px;
    list-style:none;
    padding:0;
  }


  .draw {
    width: 175px;
    height: 85px;
    border-radius: 0px;
    border: solid 2px #071bb0;
    background-color: #ffffff;
    text-align: center;
    border-left: 0px ;
  }

  .round2 {

           height: 100px;
  }

  .semifinal {

    height: 210px;
}

  .final {

      height: 1px;
      border-top: 0px ;
    }
    
    li.game-top{ border-bottom:0px solid #aaa; }
    li.game-bottom{ border-bottom:0px solid #aaa; }

</style>
<body>
    
    <h1>2024 Santa Clara Tennis Doubles</h1>
    <main id="tournament">

      <ul class="round round-1">
        <li class="game-top">Reveno-Rinaldi <span></span> </li>
      <li class="draw"></li>
      <li class="game-top">Maybery-Stevens<span></span> </li>

        <li class="spacer">&nbsp;</li>

        <li class="game-top">Robinson-Jones<span></span> </li>
      <li class="draw"></li>
      <li class="game-top">Kardashian-Lee<span></span> </li>
      
      <li class="spacer">&nbsp;</li>
      <li class="game-top">Etcheberry-Liu<span></span> </li>
      <li class="draw"></li>
      <li class="game-top">Hoggart-Molseed<span></span> </li>
      <li class="spacer">&nbsp;</li>
      <li class="draw"></li>
      </ul>
        

      <ul class="round round-2">
        <li class="spacer">&nbsp;</li>
        <li class="game game-winner">Reveno-Rinaldi <span>6-2,3-6,1-0</span> </li>
        <li class="draw round2"></li>
        <li class="game game-winner">Robinson-Jones <span>6-2,6-4</span> </li>
        <li class="spacer">&nbsp;</li>
        <li class="game game-winner">Hoggart-Molseed<span>6-2,retired</span> </li>
        <li class="draw round2"></li>
        <li class="game game-winner">Bell-Brunkhorst<span></span> </li>
        <li class="spacer">&nbsp;</li>


        </ul>

        <ul class="round round-3">
          <li class="spacer">&nbsp;</li>
          <li class="game game-winner">Reveno-Rinaldi <span>6-2,3-6,1-0</span> </li>
          <li class="draw semifinal"></li>
          <li class="game game-winner">Hoggart-Molseed <span>6-2,7-5</span> </li>
          <li class="spacer">&nbsp;</li>
        </ul>
                 

        <ul class="round round-4">
          <li class="spacer">&nbsp;</li>
          <li class="game game-winner">Hoggart-Molseed <span>6-2,7-6</span> </li>
          <li class="draw final "></li>
          <li class="spacer">&nbsp;</li>
        </ul>


    </main>








</body>
</html>