<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Draw</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="./css/draw.css" >

</head>
<style>

.round{
    display:flex;
    flex-direction:column;
    justify-content:center;
    width:200px;
    list-style:none;
    padding:0;
  }


  .draw {
    width: 175px;
    height: 85px;
    border-radius: 0px;
    border: solid 2px #071bb0;
    background-color: #ffffff;
    text-align: center;
    border-left: 0px ;
  }

  .round2 {

           height: 100px;
  }

  .semifinal {

    height: 210px;
}

  .final {

      height: 1px;
      border-top: 0px ;
    }
    
    li.game-top{ border-bottom:0px solid #aaa; }
    li.game-bottom{ border-bottom:0px solid #aaa; }

</style>
<?php
    $p1 = "Finnegan-Rinaldi";
    $p2 = "Mayberry-Stevens";
    $p3 = "Robinson-Jones";
    $p4 = "Bloom-Lee";        

    $p5 = "Hoggatt-Molseed";        
    $p6 = "Velshi-Xia";        
    $p7 = "Rubio-Reagan";        
    $p8 = "Conway-Stefanik";        

    $semi1 = $p1; 
    $score1 = "6-1,6-3";

    $semi2 = $p4;
    $score2 = "6-2,6-2";

    $semi3 = $p5;
    $score3 = "6-3,6-2";
    $semi4 = $p8;
    $score4 = "6-0,6-2";

    $f1 = $p4;
    $f2 = $p5;
    $fscore1="6-2,(ret)";
    $fscore2="2-6,6-2,1-0";
    
    $w = $f2;
    $wscore="6-2,2-6,1-0";
    
?>
<body>
    
    <h1>2024 Santa Clara Tennis Doubles</h1>
    <main id="tournament">

      <ul class="round round-1">
        <li class="game-top"><?php echo($p1); ?> <span></span> </li>
      <li class="draw"></li>
      <li class="game-top"><?php echo($p2); ?> <span></span> </li>

        <li class="spacer">&nbsp;</li>

        <li class="game-top"><?php echo($p3);?><span></span> </li>
      <li class="draw"></li>
      <li class="game-top"><?php echo($p4);?> <span></span> </li>
      
      <li class="spacer">&nbsp;</li>
      <li class="game-top"><?php echo($p5);?> <span></span> </li>
      <li class="draw"></li>
      <li class="game-top"><?php echo($p6);?> <span></span> </li>
      <li class="spacer">&nbsp;</li>
      <li class="game-top"><?php echo($p7);?> <span></span> </li>
      <li class="draw"></li>
      <li class="game-top"><?php echo($p8);?> <span></span> </li>
    </ul>
        

      <ul class="round round-2">
        <li class="spacer">&nbsp;</li>
        <li class="game game-winner"><?php echo($semi1); ?> <span><?php echo($score1);?> </span> </li>
        <li class="draw round2"></li>
        <li class="game game-winner"><?php echo($semi2); ?> <span><?php echo($score2);?></span> </li>
        <li class="spacer">&nbsp;</li>
        <li class="game game-winner"><?php echo($semi3); ?> <span><?php echo($score3);?> </span> </li>
        <li class="draw round2"></li>
        <li class="game game-winner"><?php echo($semi4); ?><span><?php echo($score4); ?> </span> </li>
        <li class="spacer">&nbsp;</li>


        </ul>

        <ul class="round round-3">
          <li class="spacer">&nbsp;</li>
          <li class="game game-winner"><?php echo($f1); ?> <span><?php echo($fscore1); ?> </span> </li>
          <li class="draw semifinal"></li>
          <li class="game game-winner"><?php echo($f2); ?> <span><?php echo($fscore2) ?> </span> </li>
          <li class="spacer">&nbsp;</li>
        </ul>
                 

        <ul class="round round-4">
          <li class="spacer">&nbsp;</li>
          <li class="game game-winner"><?php echo($w); ?><span><?php echo($wscore);?></span> </li>
          <li class="draw final "></li>
          <li class="spacer">&nbsp;</li>
        </ul>


    </main>








</body>
</html>