<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>



</head>
<body class="BackEmail">
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage"  src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12 "> 
            <center>
                  <?php include "./imports_/title.php" ?>
                  
            </center>
            </div>
    </div>


</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-2"> </div> 
            <div class="col-sm-8 NavLink"> 
                   <?php include "imports_/private.php" ?>
            </div>

      <div class="col-sm-2"> </div> 
      </div>
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  



  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-1">
            <p>
     

        
        

        </div>
        <div class="col-sm-10 ">

        <?php
               include("./library/include.inc");
               include("./members_/email.php");
        ?>

        </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm NavLink">
        
        <?php
           include "./imports_/footer.php"
        ?>
        
        
        </div>


      
</body>
</html>