<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>
<!--
      Transparent image
      https://onlinepngtools.com/

-->


</head>
<body class="Back">
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage" src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12"> 
            <center>
                <?php include "./imports_/title.php" ?>
            </center>
      </div>
    </div>


</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 

                  <?php include "./imports_/navlink.php" ?>
             </div>

      <div class="col-sm-1"> </div> 
      </div>
  
  
  </div>

  <div class="container-sm ">
      <div class="row">
            <div class="col-sm-12"> &nbsp;</div> 
            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  



  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-3 LeftBar Link">
            <p><br>
                  Upcoming Events 
                  <p>
              
                     <p>
    
                        Board Schedule: <br/>
                        @ 7:00 pm via <a href="https://zoom.us/download">Zoom </a>
                        <p>
                        Tuesday Jan 14, 2025 <br/>
                        Tuesday April 15, 2025<br/>
                        Tuesday June 24,2025<br>
                        Tuesday Oct 28,2025 <br/>
<!--
  Tuesday Feb 13, 2024 <br/>
                        Tuesday April 23, 2024<br/>
                        Tuesday June 25,2024<br>
                        Tuesday Sept 24,2024 <br/>


-->
                        <p> ________________________________</p>
                        <p>
  
                              Monthly  Drop-In Clinics run April-September (Friday) @7:30-9:00 pm (Courts 7 & 8)</p>
                              <p>
                              2024 Clinic Schedule:
                              <p>
                                    Friday April 11, 2025 <br />
                                    Friday May 16, 2025 <br />      
                                    Friday June 13, 2025 <br />
                                    Friday August 22, 2025 <br />
                                    Friday September 19, 2025 <br />

<!-- 
                                    Friday April 12, 2024 <br />
                                    Friday May 17, 2024 <br />      
                                    Friday June 14, 2024 <br />
                                    Friday August 23, 2024 <br />
                                    Friday September 20, 2024 <br />
-->
                                    <p>
                                          <p> ________________________________</p>
                                          Mixer Schedule: <br />
                                          Held at the SC Tennis Center<br> 9 am-12 noon on courts 6-8 
                                          <p>
                                          Saturday March 22, 2025<br/>
                                          Saturday April 12, 2025 <br />
                                          Saturday May 3, 2025 <br><br />
                                          Saturday June 14, 2025 <br />
                                          Saturday July 12, 2025 <br>(Bob Hughes 
                                          Memorial Pig-Out) <br/>
                                          Saturday July 19, 2025 <br>(Team Tennis Crts. 5-8) <br/>
                                          Saturday August 23, 2025  <br/>
                                          Saturday September 20, 2025<br />                                          
                                          Saturday October 11, 2025<br />
<!--
                                          Saturday March 23, 2024<br/>
                                          Saturday April 13, 2024 <br />
                                          Saturday May 4, 2024 <br><br />
                                          Saturday June 15, 2024 (Fatima Lunch)<br />
                                          Saturday July 13, 2024 <br>(Bob Hughes 
                                          Memorial Pig-Out) <br/>
                                          Saturday August 24, 2024 (Ice Cream) <br/>
                                          Saturday September 21, 2024<br />                                          
                                          Saturday October 12, 2024<br />
-->                                          
                                          <p> ________________________________</p>
                                          Thursday November 14 Year end Dinner 
                                          <p>&nbsp;<br>

        </div>
        <div class="col-sm-8">
  
            <p>

               Welcome to the Santa Clara Tennis Club.  The club offers several opportunities
               for tennis play.  Activities include monthly Friday clinics, Saturday tennis socials
               and USTA league teams.  Some of the socials are specials -in addition to great tennis 
               we have catered food from local restaurants, including lunch
               from  <a href="https://www.yelp.com/biz/jcs-famous-bbq-san-jose?start=40" >
               JC's Barbecue</a> for the annual July Pig-out</a>.  In previous years, we had barbecue from 
               <a href="https://www.armadillowillys.com/">Armadillo Willys </a>  ,
               <a href="https://www.smokingpigbbq.net">The Smoking Pig</a> &nbsp; and
               <a href="https://www.smokedoutbbq.net">Smoked Out Barbecue</a>.


               <p>


               To celebrate Cinco de Mayo we feasted on birria tacos/rice/beans and salad from
               <a href="https://www.tostadassj.com/">Tostadas </a>.  
                To cool down during a hot August we had a special tennis social with ice cream from
               <a href="https://www.rockosicecreamtacos.com/">Rocko's in Santa Clara</a>!
               We are the <italics>only</italics> tennis club to have live music at our
               events.  The July Pigout barbecue featured Margie Wong of <a href="https://www.facebook.com/margiewongmusic/">
                  Going Vertical Music
               </a>.

               <style>

hr {
            position: relative;
            top: 20px;
            border: none;
            height: 2px;
            background: red;
            margin-bottom: 50px;
        }

        </style>


            <p>
<!--
            <h4>LAST 2023 CLINIC AND MIXER ! </h4>
                      <div style="font-size:1.2em">
                      <p>For more information read your monthly newsletter.
                      <p>
                       Friday, October 13  @ 7:30pm Santa Clara Tennis Center</br>
                       Free for members, $5 for non-members
                       <p>
                       Saturday, October 14 @9 am Santa  Clara Tennis Center<br>
                       $5 for members
                  </div>  



               <p><h3>July 2024 Pigout</h3></p>
               <a href="./dinner">
               -->              

               <p>
<!--
               <picture>
   <img  src="./images/chinastix.jpg" alt="" class="ResponsiveImage china" >

  </picture>
      -->

<!--
  <a href="./dinner">
  <p>
      <center>
            <article>
               <h4> 2024 year end dinner </h4>
               <h4> China Styx in Santa Clara  </h4>
               <h4> Thursday, November 14 6-8 pm  </h4>
            </article>
      </center>
</a>
-->

<style>

h3 {
            position: relative;
            top: 20px;
            border: none;
            height: 2px;
            background: purple;
            margin-bottom: 50px;
        }

        </style>

<h3 />
<p>
      <center>
<!--      <a href="./teamtennis.phtml">  -->

      <a href="./signup">
            <article>
            <p><br>
               <h2> Join us for Team Tennis in December </h2>
               <h4> Santa Clara Tennis Center </h4>
               <h4> Sunday December 8 1:30 pm - 4 pm  </h4>
               <h4> $5 for SCTC members, $10 for guests</h4>
               <h4> No partner needed, just </h4>
            <h4> Sign up at sctennisclub.org/signup</h4>   
            </article>
         </a>

      </center>

      <!--

<a href="./signup"><img class="ResponsiveImage" src="./images/icecreamsocial.png"></a>
               <p>
               <span style="color:rgb(205, 52, 53) ; font-size:1.75em ">
                  <br/>
                  </span>

                  <h3 style="font-size: 1.2em ">
    Enjoy some  tennis and <b>ice cream</b>  on the courts with fellow members for
    social mixed doubles round robin play at Santa Clara Tennis Center on
    August 24, 2024 , 9-12 noon on courts #6-#8. 
      -->
    <!--    
    Sign up early before entries close!
    If you just &#x1F497; ice cream, you may
    sign up for the ice cream only option! <br/>
    Signup page is at <a href="http://www.sctennisclub.org/signup">www.sctennisclub.org/signup</a>
-->  




                  <!--
                  <span style="color:rgb(205, 52, 53) ; font-size:1.75em ">
                  Enjoy Tennis and  barbecue from <a href="https://www.smokedoutbbq.net/"> Smoked Out Barbecue </a> <br/>
                   </span>
-->

<!--
                   <span style="color:rgb(206, 52, 51)  ; font-size:1.75em">

                  Saturday , July 13  at  Santa Clara Tennis Center
                        

                  <a href="https://maps.app.goo.gl/Qaaa5JjCyEp4woit5">
                  
                  Santa Clara Tennis Center </a><br/>
-->
            </span>
             <p>
          
<!--
             <span style="color:rgb(206, 52, 51)  ; font-size:1.75em">
                  First Come First Served! <br/>
                  </span>
                  <p>


                  <a href="./signup" style="color:rgb(126, 61, 24)  ; font-size:2em">Sign up here </a> <br>
                  <p/>
                   <br>   

                  <span style="color: rgb(206, 68, 33)  ; font-size:1.75em"> Signups open soon</span>
-->
            </span>
                  </h1>
        </div>

        <div class="col-sm-1 RightBar">
        </div>


      </div>

      <div class="container-sm ">
            <?php
         //  include "./imports_/footer.php";
          ?>
        
        
        </div>

      
</body>
</html>