<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <link rel="stylesheet" href="./css/draw.css" >

      <title>Santa Clara Tennis Club</title>

<script>
//https://stackoverflow.com/questions/43043113/how-to-force-reloading-a-page-when-using-browser-back-button
window.addEventListener( "pageshow", function ( event ) {
  var historyTraversal = event.persisted || 
                         ( typeof window.performance != "undefined" && 
                              window.performance.navigation.type === 2 );
  if ( historyTraversal ) {
    // Handle page restore.
//    alert("reload")
    window.location.reload();
  }
});


</script>

</head>
<body class="Back" >
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage"  src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12 "> 
            <center>
                  <?php include "./imports_/title.php" ?>
             </center>
    </div>
     </div>

</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-2"> </div> 
            <div class="col-sm-8 NavLink"> 
            <?php include "./imports_/debug.php" ?>  
              
             </div>

      <div class="col-sm-2"> </div> 
      </div>
  
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  

  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-1 ">
            <p>
     
        </div>
        <div class="col-sm ">

        <?php
 //              include("./library/include.inc");
 //              include("./members_/memberlist.php");
        ?>
 
<style>


  main{
    display:flex;
    flex-direction:row;
  }


</style>
   <?php
           include "./library/include.inc";
           include "./library/dbevent.inc";

           function TEXTER($v){

            echo("$v <br>");
           }

           $v = 0;

           if( !empty($_GET['mode']) ){
                $v=$_GET["mode"];
           }
            
           if($v == 0){

            TEXTER("<h5>2024 Tournament (Mx 6.5/7.5)</h5>");
                 TEXTER("<h5>Rules</h5>");
                 TEXTER("All players must be Santa Clara Tennis Club members");
                 TEXTER("All matches must be played at Santa Clara Tennis Center");
                 TEXTER("All NTRP ratings eligible");
                 echo "<p>";
                 TEXTER("<h5>Point System</h5>");

                 TEXTER("New entries receive a staring point total whch is approxmately the average points of particpiants in the division  minus 30%");
                 TEXTER("The winner receives 1/2 the current point total of one of the  participants -- whch ever is higher");
                 TEXTER("The loser  receives 1/2 the current point total of one of the participants -- whch ever is lower");


                 echo "<p>";
                 TEXTER("<h7>Examples:</h7>");

                 TEXTER("If #1 plays #10 and wins -- the points won by #1 is 1/2 the #1 point total");
                 TEXTER("If #10 plays #1 and wins -- the points won by #10 is 1/2 the #1 point total");



                 echo ("<hr/>");

                 echo ("<p>");
                 TEXTER("<h5>Suggested: </h5>");
                 TEXTER("Finish matches in one 1-1/2 hour court reservation, so play 3rd set super-tie");
                 TEXTER("Split the court fees");
  
           }else if($v == 1) {

               include "./ladder_/ladder_participants.php";
               
           }else if($v == 2){

            include "./ladder_/ladder_report_mens.php";           

          }else if($v == 3){  

            include "./ladder_/ladder_report_womens.php";           

          }else if($v == 4){  

            include "./ladder_/ladder_resultsphp";                       

          }else if($v == 5 ){

            include "./ladder_/ladder_email.php";
      
          }else if($v==6){

            include "./ladder_/ladder_enter.php";


           } else if($v==7){

            //include "./tournament_/tournament_report_womens.php";

          } else if($v==99){
// private method to re-initialize
//            include "./tournament_/reorder.php";
          //  include "./tournament_/tournament_report.php";

      }


?>
  

</div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
 
        <?php
         include "./imports_/footer.php";
        ?>

        
        </div>







<body>
      
</body>
</html>