<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
      <script src="http://code.jquery.com/jquery-latest.min.js"></script>


      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>

      <script>
function AJAX(user,pw , state){

// DETERMINE WHETHER NON-RESIDENTS CAN APPLY  ***************
var request = $.ajax({
    url: "./members_/checkemail.php",
    type: "post",
    data:{ user: user , pw:pw , state:state },
    dataType: "html"

   });

  request.done( function(msg){


       if( msg == "yes"){
            $("#MemberList").css("display","inline");
      }else{
            $("#MemberList").css("display","none");
            alert("Cant find " + msg )
       }



  });

  request.fail(function( jqXHR, textStatus){

//   alert("Request failed; " + textStatus);

  });






}


function AJAX_CHECKEMAIL( user,pw ,state)
{
      
       
       $.ajax(

                  {

                        url: "./members_/checkemail.php",
                        type: "post",
                        data:{ user: user , pw:pw , state:state },
                        contentType: "application/json",

                        success: function(data){
                            if( data.status == "success"){
                              alert("good")
                              return true;
                            }else if( data.status == "error"){
                              alert("alert error")
                              return false;
                            }else{
                              alert("alert else = " + data.status)

                            }
                              
                        },
                        error: function(){
                              alert("Error occured")
                        }
                       

                  }
       )// ajax


}// AJAX_EMAILER


            function check( _user, _pw){
                  let users = {
                    "granola" : "playstation",
                    "strawberry" : "playstation"

              }

                  for( var key in users){
                     if( key ==_user && users[key] == _pw ) return true
                  }

//                  retv = AJAX_CHECKEMAIL( _user, _pw , 2)
                  retv = AJAX( _user, _pw , 2)
                  retv="yes"
                  return retv

            }

            $(document).ready( function(){
                  $("#MemberList").css("display", "none");

                  $("#but_submit").click( function() {
                     let user = $("#user").val()
                     let pw = "playstation" //$("#pw").val() 
                     if( check(user,pw) == "yes"){
                        $("#MemberList").css("display","inline");
                     }else{

                        alert("ERROR: " +  user );

                  }


                  })


            })
      

      </script>


</head>
<body class="Back" >
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage"  src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12 "> 
            <center>
                  <?php include "./imports_/title.php" ?>
             </center>
    </div>
     </div>

</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 
                  <?php include "./imports_/navlink.php" ?>
             </div>

      <div class="col-sm-1"> </div> 
      </div>
  
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  
<!--  **************************************************************  -->

  <div class="container-sm ">
      <div class="row">
            <div class="col-sm-2">&nbsp;</div>
               <div class="col-sm-8 text-center">
                <?php include "./members_/user.php"?>
                  <div>
                   <input type="button" value="Submit" class="btn btn-primary" id="but_submit" />
                  </div>
               </div>
            <div class="col-sm-2">&nbsp;</div>

      </div>
  <div>

 <!--  **************************************************************  -->
  <div class="container" id="MemberList" >
      <div class="row align-items-start">
        <div class="col-sm-1 ">
            <p>
     
        </div>
        <div class="col-sm ">

        <?php
               include("./library/include.inc");
               include("./members_/memberlist.php");
        ?>


        </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
 
        <?php
         include "./imports_/footer.php";
        ?>

        
        </div>







<body>
      
</body>
</html>