<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara dTennis Club</title>



</head>
<body class="Back">
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage" src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12">
        <center>
            <?php include "./imports_/title.php" ?>
       </center>
    </div>
      </div>

</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 
                <?php include "./imports_/navlink.php" ?>
            </div>

      <div class="col-sm-1"> </div> 
      </div>
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-2"> &nbsp;</div> 
            <div class="col-sm-8">

            <h3>PAST MIXERS</h3>

            <h3><a href="javascript:Toggle('2023July');"> July 15, 2023 ( Bob Hughes Memorial Pig-Out) </a></h3>
             <div id="2023July">
             <p>
                 A special pig-out with music! Margie Wong of
             <a href="https://www.facebook.com/margiewongmusic">
             Going Vertical Music</a> provided entertainment 
             while tennis players enjoyed barbecue from <a href="https://www.yelp.com/biz/jcs-famous-bbq-san-jose">JC's Barbecue </a>. 
                 <p/>
             <a href="https://www.youtube.com/watch?v=Cn0VRKA5jwk"> <img src="./images/duo.gif"><br/>
             </a>


            </div> 


             <div class="col-sm-2"> &nbsp;</div> 
      </div>
  
  
  </div>
  



  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-3 ">
            <p>
     

        
        

        </div>
        <div class="col-sm ">



        </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
        <?php
        include "./imports_/footer.php";
         ?>
        
        
        </div>







<body>
      
</body>
</html>