<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>


     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
     <script src="https://code.jquery.com/jquery-latest.min.js"></script>

<script defer>

function deadline(){

//   final = new Date('2025-04-23T23:30:00');
   final = new Date('2025-04-25T00:01:00');

    epoch= final.getTime()
     
   const date = new Date()
   current = date.getTime()

   console.log(epoch)
   console.log(current)
     
   finished =0;
   if ( current > epoch) finished=1
   
   xc =   current  >  epoch
   console.log( current + " >" + epoch + "(" + xc + ")" )
   return finished

}

//           ASYNCHRONOUS AJAX to get number of participants
             function resolver(_data){
                  console.log( "resolver = " + _data )
                  if(_data > 26){
//                 Deactivates button
                        $("#LunchButton").text('Entries are closed (' + _data + ' )');
                        $("#LunchButton").prop('disabled', true);
                  }else{
//                 Activates button
//                        $("#LunchButton").text( 'Submit to go to Paypal ');
//                        $("#LunchButton").prop('disabled', false);
            }

            }

async function  fetchData( ) {
                   return new Promise((resolve, reject) => {

                      let user = "tennis.mutt@gmail.com"
                      let pw  = "password"
                      $.ajax({
                        
                              url: "./signup_/signup_count.php",
                              type: "post",
                              data:{ user: user , pw: pw },
                              dataType: "html",
                              success: (data) => {
                                      resolver(data);
                              },
                                    error: (error) => {
                                       console.log(error)
                                       //   reject(error);
                                    }
                });
              });
            }



document.addEventListener("DOMContentLoaded", function(){
    console.log("DOMContentLoaded")
    finished = deadline();
    
     console.log("finished " + finished)
    //    finished=1

    if(finished == 0){
            $("#LunchButton").text('Submit to go to Paypal');
            $("#LunchButton").prop('disabled', false);
      }else{
            $("#LunchButton").text( 'Entries are closed');
            $("#LunchButton").prop('disabled', true);
    }

//   If entries exceede (>26) closes entries
     fetchData();
});

 </script>

</head>
<body class="Back"  >
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
            <div class="col-sm-10 ">
                  <center> <img  class="ResponsiveImage" src="images/banner_main2.png"></center> 
            </div>
      </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12"> 
            <center>
            <?php include "./imports_/title.php" ?>
        </center>
      </div>
    </div>


</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 
                  <?php include "./imports_/navlink.php" ?>
            </div>

      <div class="col-sm-1"> </div> 
      </div>
  
  
  </div>

  <?php 
    
  ?>


  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-2"> &nbsp;</div> 
            <div class="col-sm-8">
             <hr/>     
            <main>

            
             <?php

                $MEMBER_FEE="10.00";    // "5.00";
                $ICECREAM_FEE="5.50";  //"5.50";
                $GUEST_FEE = "10.00";  //"10.00" ;
          


                include "./library/include.inc";
                include "./library/paypal.inc";
                include "./library/emailer.php"; 

                include "./library/free_paypal.inc";
 //               include "./signup_/pigout.php";

//              include "./signup_/signup_icecream.php";


// Change the images and verbiage (this for pigout)
//               include "./signup_/signup_free.php";

//             switch the tables bewteen MIXER_PAYMENT  and MIXER_PENDING
               define("TABLE_MIXER_OR_PENDING" , TABLE_MIXER_PENDING);
//             define("TABLE_MIXER_OR_PENDING" , TABLE_MIXER);

// ok
               include "./signup_/signup_lunch.php";

               include "./signup_/signup_participants_lunch.php";



                ?>
            </main>

             <hr/>     
             </div> 
      
      
             <div class="col-sm-2"> &nbsp;</div> 


            </div>
  
  
  </div>
  



  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-3 ">
            <p>
        </div>
        <div class="col-sm ">
        </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
            <?php
            include "./imports_/footer.php";
          ?>
        
        
        </div>


      
</body>
</html>