<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>

      
    <!-- Google reCAPTCHA CDN -->
    <script src= 
      "https://www.google.com/recaptcha/api.js" async defer> 
    </script> 

</head>
<body class="Back">
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
            <div class="col-sm-10 ">
                  <center> <img  class="ResponsiveImage" src="images/banner_main2.png"></center> 
            </div>
      </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12"> 
            <center>
            <?php include "./imports_/title.php" ?>
        </center>
      </div>
    </div>


</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 
                  <?php include "./imports_/navlink.php" ?>
            </div>

      <div class="col-sm-1"> </div> 
      </div>
  
  </div>


    



  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-2"> &nbsp;</div> 
            <div class="col-sm-8">
             <hr/>     
            <main>
<iframe style="width:85% ; height:70em " 
src="https://forms.gle/qiFYhbWUtJxvFr3cA">
</iframe>
            
<iframe style="width:85% ; height:60em" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSUDh73IOVUvuUl_EAkBWzciV_pv8dOxlh4cqilJjVprMAE4ti0MIyk1EmKNMr7nTZ4ITtU3CqpJynO/pubhtml?widget=true&amp;headers=false"></iframe>

    <!--
<iframe style="width:75% ; height:400em " 
src="https://docs.google.com/spreadsheets/d/1s_3zr8qdCzYlO1vjdVLP_fw5mqlOgfrlmN5Tq2Zt31o/edit?resourcekey=&gid=1489952670#gid=1489952670">
-->
</iframe>
             <?php

                $MEMBER_FEE="5.00";    // "5.00";
                $ICECREAM_FEE="5.50";  //"5.50";
                $GUEST_FEE = "10.00";  //"10.00" ;

?>


             <hr/>     
             </div> 
      
      
             <div class="col-sm-2"> &nbsp;</div> 


            </div>
  
  
  </div>
  



  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-3 ">
            <p>
        </div>
        <div class="col-sm ">
        </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
            <?php
            include "./imports_/footer.php";
          ?>
        
        
        </div>








      
</body>
</html>
