<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>

    <!-- Google reCAPTCHA CDN -->
    <script src= 
      "https://www.google.com/recaptcha/api.js" async defer> 
    </script> 

</head>
<body class="Back">
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
            <div class="col-sm-10 ">
                  <center> <img  class="ResponsiveImage" src="images/banner_main2.png"></center> 
            </div>
      </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12"> 
            <center>
            <?php include "./imports_/title.php" ?>
        </center>
      </div>
    </div>


</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-1"> </div> 
            <div class="col-sm-10 NavLink"> 
                  <?php include "./imports_/navlink.php" ?>
            </div>

      <div class="col-sm-1"> </div> 
      </div>
  
  
  </div>

  <?php 
    
  ?>


  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-2"> &nbsp;</div> 
            <div class="col-sm-8">
             <hr/>     
            <main>


                      <!-- div to show reCAPTCHA -->

             <?php

                $MEMBER_FEE="10.00";    // "5.00";
                $ICECREAM_FEE="5.50";  //"5.50";
                $GUEST_FEE = "10.00";  //"10.00" ;

                include "./library/include.inc";
                include "./library/paypal.inc";
                include "./library/emailer.php"; 

                include "./library/free_paypal.inc";


// Change the images and verbiage (this for pigout)
//               include "./signup_/signup_free.php";

//             switch the tables bewteen MIXER_PAYMENT  and MIXER_PENDING
               define("TABLE_MIXER_OR_PENDING" , TABLE_MIXER_PENDING);
//             define("TABLE_MIXER_OR_PENDING" , TABLE_MIXER);


               include "./signup_/signup_buffet.php";
               include "./signup_/signup_participants_buffet.php";


                ?>
            </main>

             <hr/>     
             </div> 
      
 


           <div class="col-sm-2"> &nbsp;</div> 


            </div>
  
  
  </div>
  



  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-3 ">
            <p>
        </div>
        <div class="col-sm ">
        </div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
            <?php
            include "./imports_/footer.php";
          ?>
        
        
        </div>


      
</body>
</html>