<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/index.css" >

      <title>Santa Clara Tennis Club</title>



</head>
<body class="Back" >
<p>

</p>
<div class="container-sm ">
      <div class="row">
      <div class="col-sm-1">  </div>            
       <div class="col-sm-10 "><center> <img  class="ResponsiveImage"  src="images/banner_main2.png"></center> </div>
      <div class="col-sm-1">
      </div>
      </div>  
      
      </div>

<div class="container-sm Title">
    <div class="row">
      <div class="col-sm-12 "> 
            <center>
                  <?php include "./imports_/title.php" ?>
             </center>
    </div>
     </div>

</div>

<div class="container-sm ">
      <div class="row">
            <div class="col-sm-2"> </div> 
            <div class="col-sm-8 NavLink"> 
                  <?php include "./imports_/navlink.php" ?>
             </div>

      <div class="col-sm-2"> </div> 
      </div>
  
  
  </div>

  <div class="container-sm ">
      <div class="row">

            <div class="col-sm-12"> &nbsp;</div> 
      </div>
  
  
  </div>
  

  <div class="container">
      <div class="row align-items-start">
        <div class="col-sm-1 ">
            <p>
     
        </div>
        <div class="col-sm ">

        <?php
 //              include("./library/include.inc");
 //              include("./members_/memberlist.php");
        ?>
 
<style>

.rectangle{
    display:flex;
    flex-direction:column;
    justify-content:center;
    width:201px;
    list-style:none;
    padding:0;
    border: 2px;
}

.draw {
  background-color: #602fd0;
  background-color: rgb(202,233,245);
  border-top: 1px solid #0091b5;
  border-right:1px solid #0091b5;
  border-left-color: #fff;
  border-right-color: #fff;
  list-style: none;
  width:200px;
  height: 50px;
  padding: 3px 30px;
  font-size: 16px;

  border: solid 1px #071bb0;
  border-left: 0px ;

}

.draw2{

      height:150px;

}
.draw3{

      height:275px;

}
.spacer {

  background-color: #602fd0;
  background-color: rgb(202,233,245);
  border-top: 1px solid #0091b5;
  border-right:1px solid #0091b5;
  border-left-color: #fff;
  border-right-color: #fff;
  list-style: none;
  width:200px;
  height: 50px;
  padding: 3px 30px;
  font-size: 16px;
  border: none;

}


li.game-top{ 
      border-bottom:0px solid #aaa; 
      list-style:none;
      width:200px;

  }


 .round{
    display:flex;
    flex-direction:column;
    justify-content:center;
    width:201px;
    list-style:none;
    padding:0;
  
  }

  main{
    display:flex;
    flex-direction:row;
  }


</style>

   <h1>2024 Mens Singles Tournament</h1>
<main id="tournament">

<ul class="round">
  <li class="spacer">
  <li class="game-top"> Carlos Alcaraz <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Tommy Paul <span></span> </li>

  <li class="spacer">  

<!--   -->
  <li class="game-top"> Danill Medvedev <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Jannik Sinner <span></span> </li>

  <li class="spacer"> 
<!--   -->

<li class="game-top">Lorenzo Musetti <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Taylor Fritz <span></span> </li>

  <li class="spacer"> 
<!--   -->
<li class="game-top"> Alex de Minaur <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Novak Djokovic  <span></span> </li>

  <li class="spacer"> 
<!--   -->



</ul>

<!-- Semi-Finals  -->
<ul class="round">
<li class="game-top"> Alcaraz <span></span> </li>
  <li class="draw draw2"></li>
  <li class="game-top"> Medvedev <span></span> </li>
  <li class="spacer"> 
  <li class="spacer"> 
<li class="game-top">L Musetti <span></span> </li>
  <li class="draw draw2"></li>
  <li class="game-top"> Djokovich <span></span> </li>
</ul>

 <!-- Finals -->
  <ul class="round">
  <li class="game-top"> Alcaraz <span></span> </li>
  <li class="draw draw3"></li>
  <li class="game-top"> Djokovich <span></span> </li>

</ul>

 <!-- Winner -->
<ul class="round">

<li class="game-top"> Alcaraz <span></span> </li>
</ul>





</main>

<h1>Womens Singles Tournament</h1>

<main>

<ul class="round">
  <li class="spacer">
  <li class="game-top"> Barbora Krejikova <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Jelena Ostapenko <span></span> </li>

  <li class="spacer">  

<!--   -->
  <li class="game-top"> Elena Rybakna <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Elina Svitolina <span></span> </li>

  <li class="spacer"> 
<!--   -->

<li class="game-top">Donna Vekic <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Lulu Sun <span></span> </li>

  <li class="spacer"> 
<!--   -->
<li class="game-top"> Jasmine Paolini <span></span> </li>
  <li class="draw"></li>
  <li class="game-top"> Emma Navarro  <span></span> </li>

  <li class="spacer"> 
<!--   -->



</ul>
<!-- Semi-Finals  -->
<ul class="round">
<li class="game-top"> Krejikova<span></span> </li>
  <li class="draw draw2"></li>
  <li class="game-top"> Rybakna <span></span> </li>
  <li class="spacer"> 
  <li class="spacer"> 
<li class="game-top">Vekic <span></span> </li>
  <li class="draw draw2"></li>
  <li class="game-top"> Paolini <span></span> </li>
</ul>

 <!-- Finals -->
  <ul class="round">
  <li class="game-top"> Krejikova <span></span> </li>
  <li class="draw draw3"></li>
  <li class="game-top"> Paolini <span></span> </li>

</ul>

 <!-- Winner -->
<ul class="round">

<li class="game-top"> Barbora Krejcikova <span></span> </li>
</ul>




</main>
</div>

        <div class="col-sm-1 RightBar">

        </div>


      </div>

      <div class="container-sm ">
 
        <?php
         include "./imports_/footer.php";
        ?>

        
        </div>







<body>
      
</body>
</html>